Add support for postgres db

diff --git a/scripts/ci b/scripts/ci
--- a/scripts/ci
+++ b/scripts/ci
@@ -1,17 +1,13 @@
 #!/bin/bash
 set -e
 
-echo $(hostname)
-
 cd $(dirname $0)
 
-export RUNTIME_DIR=../../../runtime/ci/
+# An environment is a db and test plan
+declare -A ENVIRONMENTS=${ENVIRONMENTS:-( [h2]=lite [mysql]=full [pgsql]=full )}
+declare -A RESULTS=( [h2]=0 [mysql]=0 [pgsql]=0 )
 export RUNTIME_DIR_CLEAN=true
 export CATTLE_LOGBACK_ROOT_LEVEL=error
-export CATTLE_DB_CATTLE_DATABASE=mysql
-
-: ${CATTLE_DB_CATTLE_MYSQL_PORT:=13306}
-export CATTLE_DB_CATTLE_MYSQL_PORT
 
 # Uncomment this if you're impatient
 #export CATTLE_IDEMPOTENT_CHECKS=false
@@ -59,52 +55,127 @@ run()
     echo
 }
 
+gist ()
+{
+    local result=0
+    printf "\n\e[1;35mRESULTS\e[0m\n"
+    printf "\e[1;32m%-10s %-10s Status\e[0m\n" "Database" "Plan"
+
+    for db in "${!ENVIRONMENTS[@]}"
+    do
+        if [ ${RESULTS[${db}]} -ge 1 ]; then
+            printf "%-10s %-10s \e[1;31mFAILED\e[0m\n" $db ${ENVIRONMENTS[$db]}
+            result=1
+        else
+            printf "%-10s %-10s \e[1;32mSUCCESS\e[0m\n" $db ${ENVIRONMENTS[$db]}
+        fi
+    done
+
+    exit $result
+}
+
+tear_down() {
+    echo "Shutting down agent..."
+    set +e
+    docker stop $(docker ps -q) &>> /dev/null
+    docker rm -fv $(docker ps -a -q) &>> /dev/null
+    set -e
+
+    echo "Shutting down server..."
+    pkill java
+    case $DB in
+        mysql ) service mysql stop ;;
+        pgsql ) service postgresql stop ;;
+    esac
+}
+
+test_failed ()
+{
+    cat /tmp/run.log
+    ((RESULTS[$1]++))
+}
+
 # Background to start the Docker pulls
 ./test-warm >/dev/null &
 
-run ./mysql
-
 CI=true MAVEN_ARGS='-B -q' run ./build
 
-run ./run --background
+for DB in "${!ENVIRONMENTS[@]}"
+do
 
-# Wait for completion now to ensure that images are pulled
-./test-warm
+    echo -e "\n\e[1;35mTESTING $DB\e[0m\n"
 
-export AGENT_IMAGE=$(grep bootstrap.required.image ../resources/content/cattle-global.properties | cut -f2 -d=)
-DEV_HOST=localhost:8081 ../tools/development/register-boot2docker.sh >/tmp/register.log &
+    export RUNTIME_DIR=$(pwd)/../runtime/ci-$DB/
 
-./wait-for-hosts
+    # Bootstrap Database
+    case $DB in
 
-./test -e py27 -- -m nonparallel
+        h2 )
+            ;;
 
+        mysql )
 
-threads=$(($(nproc) + 1))
-if [ $threads -gt 8 ]; then
-    threads=8
-fi
-./test -- -m "'not nonparallel'" -n $threads -v || {
-    echo Test failed
-    cat /tmp/run.log
-    echo Test failed
-    exit 1
-}
+            export CATTLE_DB_CATTLE_DATABASE=mysql
+            : ${CATTLE_DB_CATTLE_MYSQL_PORT:=13306}
+            export CATTLE_DB_CATTLE_MYSQL_PORT
+            run ./mysql --clean
+            ;;
 
-# Now test H2
+        pgsql )
 
-echo "Testing H2"
+            export CATTLE_DB_CATTLE_DATABASE=postgres
+            run ./pgsql --clean
+            ;;
 
-export RUNTIME_DIR=../../../runtime/ci-h2/
-export RUNTIME_DIR_CLEAN=true
-export CATTLE_DB_CATTLE_DATABASE=h2
-export CATTLE_TEST_HTTP_PORT=8083
-export CATTLE_TEST_HTTP_PROXIED_PORT=8084
-export CATTLE_TEST_URL=http://localhost:8083/v1/schemas
+        * )
 
-run ./run --background
-./test -e py27 -- core/test_virtual_machine.py core/test_container.py || {
-    echo Test failed
-    cat /tmp/run.log
-    echo Test failed
-    exit 1
-}
+            echo "Unknown database specified."
+            exit 1
+
+    esac
+
+    run ./run --background
+
+    # Test Environment
+    case ${ENVIRONMENTS[$DB]} in
+
+        full )
+
+            threads=$(($(nproc) + 1))
+            if [ $threads -gt 8 ]; then
+                threads=8
+            fi
+
+            # Wait for completion now to ensure that images are pulled
+            ./test-warm
+
+            AGENT_IMAGE=$(grep bootstrap.required.image ../resources/content/cattle-global.properties | cut -f2 -d=)
+            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ${AGENT_IMAGE} http://localhost:8081 >/tmp/register.log &
+
+            ./wait-for-hosts
+
+            set +e
+            ./test -e py27 -- -m nonparallel && ./test -- -m "'not nonparallel'" -n $threads -v || test_failed $DB
+            set -e
+
+            ;;
+
+        lite )
+
+            set +e
+            ./test -e py27 -- core/test_virtual_machine.py core/test_container.py || test_failed $DB
+            set -e
+            ;;
+
+        * )
+
+            echo "Unknown test plan specified."
+            exit 1
+
+    esac
+
+    tear_down
+
+done
+
+gist
